server:
  port:8080

spring:
  application:
    name: project-1-backend
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:client}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:toor}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



